/**
 * Single source of truth for the site's security policy.
 *
 * Two layers, kept deliberately non-overlapping so browsers (which enforce
 * the *intersection* of every CSP they receive) never contradict each other:
 *
 *  1. Per-page `<meta http-equiv="content-security-policy">` — emitted by
 *     Astro's built-in CSP (`experimental.csp` in `astro.config.ts`), which
 *     hashes every inline <script>/<style> it controls and appends the
 *     hashes to `script-src` / `style-src`. `CSP_META_DIRECTIVES` below is
 *     the rest of that policy (Astro owns script-src/style-src).
 *
 *  2. Edge response headers (`dist/_headers`, generated by the
 *     `kush-house:netlify-headers` integration) — `EDGE_CSP` carries only
 *     what a <meta> tag cannot express (`frame-ancestors`) plus harmless
 *     reinforcements, and intentionally has no script-src/style-src/
 *     default-src so it cannot clash with layer 1.
 *
 * `scripts/audit-dist.mjs` fails the build if the emitted HTML or
 * `dist/_headers` drifts from what is declared here, or if any page ships a
 * `<style>` element, a `style="…"` attribute or an `on*=` handler.
 */

/**
 * CSP directives Astro injects into every page's <meta>. `script-src` and
 * `style-src` are omitted on purpose — Astro appends them with per-page
 * hashes. No `'unsafe-inline'`, `'unsafe-eval'` or `*` anywhere.
 */
export const CSP_META_DIRECTIVES = [
  "default-src 'self'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-src 'none'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "manifest-src 'self'",
  "worker-src 'self'",
  "object-src 'none'",
  'upgrade-insecure-requests',
] as const;

/**
 * Header-only CSP. `frame-ancestors` is ignored inside a <meta>, so it must
 * ride on the response header. `base-uri` / `object-src` are duplicated
 * harmlessly. No fetch directive that could conflict with the meta policy.
 */
export const EDGE_CSP = "frame-ancestors 'none'; base-uri 'self'; object-src 'none'";

/** Response headers Netlify must send (written to `dist/_headers`). */
export const SECURITY_HEADERS: Readonly<Record<string, string>> = {
  'Content-Security-Policy': EDGE_CSP,
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'X-Frame-Options': 'DENY',
  'Permissions-Policy':
    'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
  'X-DNS-Prefetch-Control': 'off',
};
